<<<<<<<
%%%%%%%
 [package]
 name = "mdbook-trpl-listing"
 version = "0.1.0"
 edition = "2021"
 
 # See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
 
 [dependencies]
 clap = { version = "4.5.4", features = ["derive"] }
 mdbook = { version = "0.4.37" }
 pulldown-cmark = { version = "0.10.3", features = ["simd"] }
 pulldown-cmark-to-cmark = "13.0.0"
 serde_json = "1.0.117"
 thiserror = "1.0.60"
 toml = "0.8.12"
 xmlparser = "0.13.6"
+
+[dev-dependencies]
+assert_cmd = "2.0.14"
+++++++
>>>>>>>
